project:
  type: website
  output-dir: docs

website:
  title: "Amanda Alvarez"
  favicon: "images/pinapinguina.png"
  navbar:
    left:
      - href: index.qmd
        text: About
      - newsletter.qmd
      - publications.qmd
    right:
      - icon: bluesky
        href: https://bsky.app/profile/gecky.me
        aria-label: Bluesky
      - icon: mastodon
        href: https://data-folks.masto.host/@gecky
        aria-label: Mastodon
  body-footer:
    <div id='data-ring-dot-list'>
    <script type="text/javascript" src="https://randyau.github.io/datawebring/onionring-variables.js"></script>
    <script type="text/javascript" src="https://randyau.github.io/datawebring/onionring-widget.js"></script>
    </div>
  page-footer:
    left: "&copy; 2024 Amanda Alvarez"

format:
  html:
    theme: datacos.scss
    css: datacos.scss
    toc: true