project:
  type: website
  output-dir: docs

website:
  title: "Amanda Alvarez"
  favicon: "images/pinapinguina.png"
  navbar:
    left:
      - href: index.qmd
        text: About
      - newsletter.qmd
      - publications.qmd
    right:
      - icon: mastodon
        href: https://data-folks.masto.host/@gecky
        aria-label: Mastodon
  page-footer:
    left: "&copy; 2023 Amanda Alvarez"

format:
  html:
    theme: datacos.scss
    css: datacos.scss
    toc: true