project:
  type: website
  output-dir: docs

website:
  title: "Amanda Alvarez"
  favicon: "images/pinapinguina.png"
  navbar:
    left:
      - href: index.qmd
        text: About
      - publications.qmd
      - newsletter.qmd
    right:
      - text: "{{< fa brands bluesky >}}"
        href: https://bsky.app/profile/gecky.me
        aria-label: Bluesky
      - text: "{{< fa brands mastodon >}}"
        href: https://data-folks.masto.host/@gecky
        aria-label: Mastodon
  page-footer:
    center: <div id='data-ring-dot-list'>
        <script type="text/javascript" src="https://randyau.github.io/datawebring/onionring-variables.js"></script>
        <script type="text/javascript" src="https://randyau.github.io/datawebring/onionring-widget.js"></script>
        </div>
    left: "&copy; 2025 Amanda Alvarez"

format:
  html:
    theme: datacos.scss
    css: datacos.scss
    toc: true