baseURL = 'https://gecky.me'
languageCode = 'en-us'
title = 'Amanda Alvarez'

theme = ["github.com/theNewDynamic/gohugo-theme-ananke"]

resourceDir = "../resources"

DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 5
googleAnalytics = ""
enableRobotsTXT = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  text_color = ""
  author = ""
  favicon = ""
  site_logo = ""
  description = ""
  # choose a background color from any on this page: https://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-near-black"
  recent_posts_number = 0

[[params.ananke_socials]]
name = "mastodon"
url = "https://data-folks.masto.host/@gecky"
